spring.application.name=alpha-exam
logging.level.liquibase = INFO
spring.datasource.url=jdbc:sqlserver://pdsazuresqlserverdev.database.windows.net:1433;database=pdsazuresqldbdev;user=pdssqldbadmin@pdsazuresqlserverdev;password=h@JbmLBNVm9n2b2!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
